name: first workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the myfirstname
        run: echo "kottu"
      - name: Print the secondname
        run: echo "somaraju"
